version: '3'
services:

  api:
    build: ./account
    image: golang
    container_name: accounts_api
    ports:
      - "8081"
    depends_on: 
      - database
  
  database:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: master
      POSTGRES_DB: CNG-Account
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres/schema:/docker-entrypoint-initdb.d
networks:
  default:
    driver: bridge