version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "cng_account"
    ports:
      - "5432:5432"
    volumes:
      - ./internal/model/sql/postgres/schema:/docker-entrypoint-initdb.d
  api:
    build: .
    image: cng_account_api
    environment:
      APP_DB_HOST: "172.24.0.2"
      APP_DB_USER: "postgres"
      APP_DB_PASSWORD: "postgres"
    expose:
      - 8081
    depends_on:
      - db

networks:
  default:
    driver: bridge