version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: master
    expose:
      - 5432

  myapp:
    build: .
    image: cng_account_api
    environment:
      APP_DB_HOST: db
      APP_DB_USER: master
      APP_DB_PASSWORD: master
    expose:
      - 8081
    depends_on:
      - db