version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "cng_account"
    ports:
      - 5433:5432
    volumes:
      - ./db/postgres/schema:/docker-entrypoint-initdb.d
  
  accounts:
    image: golang:1.13
    volumes:
      - .:/app/account
    working_dir: /app/account
    env_file:
      - development.env
    command: go run . -v
    ports:
      - "8081:8081"
    links:
      - "db:db"
    expose:
      - "8081"
    restart: always
    depends_on:
      - db

networks:
  default:
    external:
      name: cng