version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "cng_account"
    ports:
      - "5432:5432"
    volumes:
      - ./internal/model/sql/postgres/schema:/docker-entrypoint-initdb.d
  api:
    image: golang:1.13
    volumes:
      - .:/app/account
    working_dir: /app/account
    env_file:
      - development.env
    command: go run . -v
    ports:
      - "8081:8081"
    depends_on:
      - db

networks:
  default:
    driver: bridge